services:
  db:
    image: postgis/postgis:17-3.5
    container_name: db-container
    restart: always
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "botDatabase"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server-container
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    restart: always

volumes:
  db-data:
  redis-data:
