FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

RUN npm install typescript

COPY . .

RUN rm -rf src/frontend

RUN npm run build

RUN npx prisma generate --schema=src/server/prisma/schema.prisma

CMD ["sh", "-c", "cd src/server && npx prisma migrate deploy && npm run server:docker"]

# CMD ["npm" , "run" , "server:docker"]